// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFd0GfDL89yemaBPTxtDdLIP5mKjMsB98',
    appId: '1:380285552019:web:c9778804fe0c888bcdd466',
    messagingSenderId: '380285552019',
    projectId: 'safetrack-3742c',
    authDomain: 'safetrack-3742c.firebaseapp.com',
    databaseURL: 'https://safetrack-3742c-default-rtdb.firebaseio.com',
    storageBucket: 'safetrack-3742c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNXHWCu90B_oERpBpYrsrD8Ts5ddYB2tM',
    appId: '1:380285552019:android:168b93ee630133e0cdd466',
    messagingSenderId: '380285552019',
    projectId: 'safetrack-3742c',
    databaseURL: 'https://safetrack-3742c-default-rtdb.firebaseio.com',
    storageBucket: 'safetrack-3742c.firebasestorage.app',
  );
}
